# How data placed into a Neural Network

In [29]:
import tensorflow as tf

In [2]:
print(tf.__version__)

2.0.0


### Scaler (0 dimension tensor)

In [4]:
import numpy as np
ক = np.array(12)
ক

array(12)

In [5]:
ক.ndim

0

### Vector (1 dimension tensor)

In [6]:
খ = np.array([12, 3, 6, 14])
খ

array([12,  3,  6, 14])

In [7]:
খ.ndim

1

### Matrix (2 dimension tensor)

In [8]:
গ = np.array([[5, 78, 2, 34, 0],
              [6, 79, 3, 35, 1],
              [7, 80, 4, 36, 2]])
গ

array([[ 5, 78,  2, 34,  0],
       [ 6, 79,  3, 35,  1],
       [ 7, 80,  4, 36,  2]])

In [9]:
গ.ndim

2

In [11]:
# পাশাপাশি একটু সরাসরি টেন্সরফ্লোতে দেখি 
import tensorflow as tf
# একটা কনস্ট্যান্ট টেন্সর বানাই, যেটা পাল্টাবে না
ঘ = tf.constant([[3, 2],
                 [5, 2]])

# ভ্যারিয়েবল টেন্সর, যেটা পাল্টাবে, মানে .Variable
ঙ = tf.Variable([[3, 2],
                 [5, 2],
                 [5, 2]])
# tf.shape(ঘ)
# আমরা শেপ দেখি
tf.shape(ঙ)

<tf.Tensor: id=10, shape=(2,), dtype=int32, numpy=array([3, 2])>

In [12]:
# আরেকটা উদাহরণ
চ = tf.constant([[1.0, 2.0, 3.0], 
                 [4.0, 5.0, 6.0]])
print(চ.get_shape())
print(চ.shape.dims)

(2, 3)
[Dimension(2), Dimension(3)]


In [13]:
ল = tf.constant([[1, 2], [3, 4]])                 
র = tf.add(ল, 1)

ল.numpy()

array([[1, 2],
       [3, 4]])

In [14]:
র.numpy()

array([[2, 3],
       [4, 5]])

In [15]:
tf.multiply(ল, র).numpy()

array([[ 2,  6],
       [12, 20]])

### 3 dimension or more tensor

In [16]:
ছ = np.array([[[5, 78, 2, 34, 0],
              [6, 79, 3, 35, 1],
              [7, 80, 4, 36, 2]],

              [[5, 78, 2, 34, 0],
              [6, 79, 3, 35, 1],
              [7, 80, 4, 36, 2]],

              [[5, 78, 2, 34, 0],
              [6, 79, 3, 35, 1],
              [7, 80, 4, 36, 2]]])

ছ

array([[[ 5, 78,  2, 34,  0],
        [ 6, 79,  3, 35,  1],
        [ 7, 80,  4, 36,  2]],

       [[ 5, 78,  2, 34,  0],
        [ 6, 79,  3, 35,  1],
        [ 7, 80,  4, 36,  2]],

       [[ 5, 78,  2, 34,  0],
        [ 6, 79,  3, 35,  1],
        [ 7, 80,  4, 36,  2]]])

In [17]:
ছ.ndim

3

## Image data shape

In [18]:
# টেন্সর শেপকে পাল্টে অন্য শেপে আনা, লাগবে এমনিস্ট ডাটাসেটে
টেন্সর = tf.constant([[3, 2],
                     [5, 2],
                     [9, 5],
                     [1, 3]])

# টেন্সরকে সারি, কলাম ধরে পাল্টাই: shape = [rows, columns]
শেপ_টেন্সর = tf.reshape(tensor=টেন্সর,
                       shape=[1, 8])

print(('টেন্সর রিশেপিং এর আগে:\n{0}').format(টেন্সর.numpy()))

print(('\nটেন্সর রিশেপিং এর পরে:\n{0}').format(শেপ_টেন্সর.numpy()))

টেন্সর রিশেপিং এর আগে:
[[3 2]
 [5 2]
 [9 5]
 [1 3]]

টেন্সর রিশেপিং এর পরে:
[[3 2 5 2 9 5 1 3]]


## Matrix multiplication in tensor

In [19]:
# উদাহরণের জন্য ম্যাট্রিক্স "ঝ"
ঝ = tf.constant([[3, 7],
                 [1, 9]])

# উদাহরণের জন্য ভেক্টর "ঞ" 
ঞ = tf.constant([[5],
                 [2]])

# ম্যাট্রিক্স মাল্টিপ্লিকেশন "ঝ" এবং "ঞ"
ঝঞ = tf.matmul(ঝ, ঞ)

print(('"ঝ" এবং "ঞ" এর ম্যাট্রিক্স মাল্টিপ্লিকেশন দিয়ে নতুন টেন্সর:\n{0}').format(
    ঝঞ
))

"ঝ" এবং "ঞ" এর ম্যাট্রিক্স মাল্টিপ্লিকেশন দিয়ে নতুন টেন্সর:
[[29]
 [23]]


***

## Fashion mnist dataset dimension, array shape

In [20]:
import tensorflow as tf
from tensorflow import keras

ফ্যাশন_এমনিস্ট = tf.keras.datasets.fashion_mnist
(ট্রেনিং_ইমেজ, ট্রেনিং_লেবেল), (টেস্ট_ইমেজ, টেস্ট_লেবেল) = ফ্যাশন_এমনিস্ট.load_data()

4423680/4422102 [==============================] - 4s 1us/step


In [21]:
print(ট্রেনিং_ইমেজ.ndim)

3


In [22]:
print(ট্রেনিং_ইমেজ.shape)

(60000, 28, 28)


In [23]:
পরিক্ষা_ইমেজ১ = ট্রেনিং_ইমেজ[10:100]
print(পরিক্ষা_ইমেজ১.shape)

(90, 28, 28)


In [24]:
পরিক্ষা_ইমেজ২ = ট্রেনিং_ইমেজ[10:100, :, :]
পরিক্ষা_ইমেজ২.shape

(90, 28, 28)

In [25]:
পরিক্ষা_ইমেজ৩ = ট্রেনিং_ইমেজ[10:100, 0:28, 0:28]
পরিক্ষা_ইমেজ৩.shape

(90, 28, 28)

In [26]:
ব্যাচ = ট্রেনিং_ইমেজ[:128]

In [27]:
ব্যাচ = ট্রেনিং_ইমেজ[128:256]

In [28]:
ব্যাচ

array([[[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]],

       [[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]],

       [[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]],

       ...,

       [[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]],

       [[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 